ELIXIR_COUNT = 10

ELIXIR_UNIT_WIDTH = 27
ELIXIR_UNIT_HEIGHT = 20

ELIXIR_START_X = 95
ELIXIR_START_Y = 625

CROPPED_ELIXIR_WIDTH = int(ELIXIR_UNIT_WIDTH * ELIXIR_COUNT)
CROPPED_ELIXIR_HEIGHT = ELIXIR_UNIT_HEIGHT
